travis:
  secure:
    BINSTAR_TOKEN: st7KipzZRZ15kdVqMifDwKfze5Kx4MjSGswRbFkmPJBOhzo9sLJYah3aCJUPHScyDLlc0wm9wblOhotN8XafXswYgHZySZCI1mjtlWJsgtkvLepyC1JOmKzI9Gk4Zrja+4Km8z5qiP1JWWd3Bv+tdBDh3szVTd0zld2qfqr81iysME9l9ayAULI1ENiPqNat0hLXU/H3TmDypfd1CLJkLq6hGY4Eu4PVKVqjuKlTTcBIVUDSPrLZSDyU3opAWW2tW/qU111Zln3B0miw267wikuCfRGQoYCZHsmms1t53iL3xgb6Vfi5SKBxonrcV83sBRtcUN/4QAgm4NTArRNb/4iGDBv8lu8XsqrFpDPOLKZRwSWkGDAiVLPoo3OIljc5Ect0oCngYMjY7LLhmmNg7c0/dBEauOe3t3hF6TbDsh9tln/wcML86MDpDPYYqGGxkx6tojGMcv2tSiI/Zd71YeXpQa7Bjh1OkjTv7AuP/h6WJK+G7MspQp2oKN5DEXAWQgATpKtQGjWJFCQg2qGm91nH/9o/flbIW1PbiDuAzBKGapvOzvg9zQ08ybEb9DrYC+XPLc4SbiCNnwnfLooig/aF45aXo9FknBcZ8W7Z2mTboAzUIufvT0AVreph77plMECNgE51qhNQXrCFnDpxP4LNBv3Po2jIkqczkwxdwek=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
